/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export type Category = { 'kids' : null } |
  { 'homeKitchen' : null } |
  { 'beauty' : null } |
  { 'sports' : null } |
  { 'fashion' : null } |
  { 'electronics' : null };
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'totalAmount' : bigint,
  'timestamp' : Time,
  'buyer' : Principal,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'seller' : Principal,
  'isActive' : boolean,
  'stock' : bigint,
  'category' : Category,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], Array<CartItem>>,
  'addToResellerCatalog' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<
    [string, string, bigint, Category, [] | [ExternalBlob], bigint],
    bigint
  >,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getResellerCatalog' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[], Order>,
  'removeFromCart' : ActorMethod<[bigint], Array<CartItem>>,
  'removeFromResellerCatalog' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateCartItem' : ActorMethod<[bigint, bigint], Array<CartItem>>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      Category,
      [] | [ExternalBlob],
      bigint,
      boolean,
    ],
    undefined
  >,
  'uploadImage' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];